name: Release Builds

on: push

env:
  SME_DEPS_COMMON_VERSION: "2021.12.09"
  DUNE_COPASI_VERSION: "releases/1.1"
  DUNE_VERSION: "releases/2.7"
  DUNE_SUPPORT_VERSION: "support/dune-copasi-v1.1.0"

jobs:
  win64-msvc:
    name: Windows 64-bit MSVC
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\smelibs'
      OS_TARGET: "win64-msvc"
      DUNE_USE_FALLBACK_FILESYSTEM: "OFF"
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*

  win32-msvc:
    name: Windows 32-bit MSVC
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\smelibs'
      OS_TARGET: "win32-msvc"
      DUNE_USE_FALLBACK_FILESYSTEM: "OFF"
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win32
          toolset: 14.0
      - name: Build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*
