name: Release Builds

on: push

env:
  SME_DEPS_COMMON_VERSION: "2022.04.29"
  DUNE_COPASI_VERSION: "releases/1.1"

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    env:
      INSTALL_PREFIX: "/opt/smelibs"
      SUDOCMD: "sudo"
      OS_TARGET: "linux"
      DUNE_USE_FALLBACK_FILESYSTEM: "ON"
      CC: "clang"
      CXX: "clang++"
    defaults:
      run:
        shell: bash
    steps:
      - name: Add llvm repo for clang 14 & install
        run: |
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-14 main"
          sudo apt update -yy
          sudo apt install -yy clang-14
      - name: Set clang version
        run: |
          sudo update-alternatives --remove-all clang || echo "nothing to remove"
          sudo update-alternatives --remove-all clang++ || echo "nothing to remove"
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100
      - uses: actions/checkout@v3
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*

  macos:
    name: MacOS
    runs-on: macos-11
    env:
      INSTALL_PREFIX: "/opt/smelibs"
      SUDOCMD: "sudo"
      MACOSX_DEPLOYMENT_TARGET: "10.14"
      OS_TARGET: "osx"
      DUNE_USE_FALLBACK_FILESYSTEM: "ON"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*

  win64:
    name: Windows 64-bit
    runs-on: windows-2022
    env:
      INSTALL_PREFIX: "/c/smelibs"
      SUDOCMD: ""
      OS_TARGET: "win64-mingw"
      DUNE_USE_FALLBACK_FILESYSTEM: "OFF"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make git dos2unix
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*

  win32:
    name: Windows 32-bit
    runs-on: windows-2022
    env:
      INSTALL_PREFIX: "/c/smelibs"
      SUDOCMD: ""
      OS_TARGET: "win32-mingw"
      DUNE_USE_FALLBACK_FILESYSTEM: "OFF"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: mingw-w64-i686-gcc mingw-w64-i686-cmake make git dos2unix
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*

  release:
    name: Upload Binaries to GitHub Release
    needs: [linux, macos, win64, win32]
    runs-on: ubuntu-latest
    # upload binaries to github release if commit is tagged
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: spatial-model-editor/sme_deps
          keep_latest: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: binaries
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
