name: Release Builds

on: push

env:
  SME_DEPS_COMMON_VERSION: "2024.04.10"
  DUNE_COPASI_VERSION: "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-20.04"
            shell: "bash"
            ccache-path: "~/.cache/ccache"
          - os: "macos-13"
            shell: "bash"
            ccache-path: "/Users/runner/Library/Caches/ccache"
          - os: "windows-2022"
            shell: "msys2 {0}"
            ccache-path: 'C:\Users\runneradmin\AppData\Local\ccache'
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: spatial-model-editor/setup-ci@v1
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.ccache-path }}
          key: ccache-${{ github.job }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: ccache-${{ github.job }}-${{ runner.os }}-
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: ./artefacts/*
          retention-days: 3

  release:
    name: Upload Binaries to GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    # upload binaries to github release if commit is tagged
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          repo: spatial-model-editor/sme_deps
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: binaries
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
